FROM node:current-alpine3.23

WORKDIR /client

COPY ./client/package.json ./client/pnpm-lock.yaml ./

RUN npm install -g pnpm@latest

RUN pnpm install

COPY ./client/ .

EXPOSE 4200

CMD ["pnpm", "start"]